### ISSUE TITLE
Use a CMS and copy the design

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/project-site#11]
We should consider to use a simple CMS (like Wordpress?) which can do everything we like and simply adapt / rework the layout.

**Comment by Croydon** [comment]
I don't think we will ever be able to find a CMS which would fit our -exact- needs. Also Wordpress is okay for a blog, just a blog. But I don't want to get in the position in which I have to modify Wordpress. The last time I looked into Wordpress code, it was just... ugly. Also since Wordpress has a way more users, it's getting attacked all the time. I don't think a Wordpress setup could be more secure, or any other big CMS.

Sorry, but I would like to continue to use a framework, which don't bind us too strong to its own coding ideals.

**Comment by movabo** [comment]
Yep, totally agree with @Croydon.
